/*  
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package foodorderproject;


import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Biromedic
 */
public class UsersScreen extends javax.swing.JDialog {
    DefaultTableModel model;
    DataBaseConnection dbc = new DataBaseConnection();
    
    /**
     * Creates new form Users
     * @param parent
     * @param modal
     */
    public UsersScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model = (DefaultTableModel)Users_Table.getModel();
        showUsers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Users_Table = new javax.swing.JTable();
        SearchBar = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name_area = new javax.swing.JTextField();
        surname_area = new javax.swing.JTextField();
        mobile_area = new javax.swing.JTextField();
        address_area = new javax.swing.JTextField();
        password_area = new javax.swing.JTextField();
        messeage_area = new javax.swing.JLabel();
        add_user = new javax.swing.JButton();
        update_user = new javax.swing.JButton();
        delete_user = new javax.swing.JButton();
        log_out_button = new javax.swing.JButton();
        show_review_btn = new javax.swing.JButton();
        go_restaurant_menu = new javax.swing.JButton();
        go_order = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);

        Users_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Name", "Surname", "Mobile", "Address", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Users_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Users_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Users_Table);
        if (Users_Table.getColumnModel().getColumnCount() > 0) {
            Users_Table.getColumnModel().getColumn(0).setResizable(false);
            Users_Table.getColumnModel().getColumn(1).setResizable(false);
            Users_Table.getColumnModel().getColumn(2).setResizable(false);
            Users_Table.getColumnModel().getColumn(3).setResizable(false);
            Users_Table.getColumnModel().getColumn(4).setResizable(false);
        }

        SearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBarActionPerformed(evt);
            }
        });
        SearchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchBarKeyReleased(evt);
            }
        });

        jLabel1.setText("Name:");

        jLabel2.setText("Surname:");

        jLabel3.setText("Mobile:");

        jLabel4.setText("Address:");

        jLabel5.setText("Password:");

        messeage_area.setForeground(new java.awt.Color(255, 102, 102));

        add_user.setBackground(new java.awt.Color(255, 204, 204));
        add_user.setForeground(new java.awt.Color(51, 102, 255));
        add_user.setText("Add New User");
        add_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_userActionPerformed(evt);
            }
        });

        update_user.setBackground(new java.awt.Color(255, 204, 204));
        update_user.setForeground(new java.awt.Color(51, 102, 255));
        update_user.setText("Update User");
        update_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_userActionPerformed(evt);
            }
        });

        delete_user.setBackground(new java.awt.Color(255, 204, 204));
        delete_user.setForeground(new java.awt.Color(255, 0, 0));
        delete_user.setText("Delete User");
        delete_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_userActionPerformed(evt);
            }
        });

        log_out_button.setBackground(new java.awt.Color(0, 255, 255));
        log_out_button.setForeground(new java.awt.Color(0, 0, 255));
        log_out_button.setText("Log Out");
        log_out_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                log_out_buttonMouseClicked(evt);
            }
        });
        log_out_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_out_buttonActionPerformed(evt);
            }
        });

        show_review_btn.setBackground(new java.awt.Color(255, 204, 204));
        show_review_btn.setForeground(new java.awt.Color(51, 51, 255));
        show_review_btn.setText("Show Reviews");
        show_review_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_review_btnMouseClicked(evt);
            }
        });

        go_restaurant_menu.setBackground(new java.awt.Color(255, 204, 204));
        go_restaurant_menu.setForeground(new java.awt.Color(51, 51, 255));
        go_restaurant_menu.setText("Go to restaurant content");
        go_restaurant_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                go_restaurant_menuMouseClicked(evt);
            }
        });

        go_order.setBackground(new java.awt.Color(255, 204, 204));
        go_order.setForeground(new java.awt.Color(102, 51, 255));
        go_order.setText("Go to Orders");
        go_order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                go_orderMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(SearchBar)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(log_out_button, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(messeage_area, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(name_area, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                            .addComponent(surname_area)
                            .addComponent(mobile_area)
                            .addComponent(address_area)
                            .addComponent(password_area))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(go_order, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(go_restaurant_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(update_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(delete_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(add_user, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                            .addComponent(show_review_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(log_out_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(surname_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_user))
                .addGap(18, 18, 18)
                .addComponent(update_user)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(mobile_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(delete_user)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(address_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(password_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(show_review_btn)
                    .addComponent(go_restaurant_menu))
                .addGap(38, 38, 38)
                .addComponent(go_order)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(messeage_area, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
    private void SearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBarActionPerformed
*/
    public void findDynamically(String search){
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        Users_Table.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }
    
    private void SearchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchBarKeyReleased
        String search = SearchBar.getText();
        findDynamically(search);      
    }//GEN-LAST:event_SearchBarKeyReleased

    
    
    public void showUsers(){
        model.setRowCount(0); 
        ArrayList<User> users = new ArrayList<User>();
        users = dbc.getTheUsers();
        if(users != null){
            for(User user: users ){
            Object[] add = {user.getId(),user.getName(),user.getSurname(),user.getMobile(),user.getAddress(),user.getPassword()};
            model.addRow(add);
            }
        }
    }
    
    private void add_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_userActionPerformed
  
       messeage_area.setText("");
       String name = name_area.getText();
       String surname = surname_area.getText();
       String mobile = mobile_area.getText();
       String address = address_area.getText();
       String password = password_area.getText();
       dbc.addUser(name,surname,mobile,address,password);
       showUsers();
       
       messeage_area.setText("User has added.");
    }//GEN-LAST:event_add_userActionPerformed

    private void Users_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Users_TableMouseClicked
        int selectedRow = Users_Table.getSelectedRow();
        name_area.setText((String) model.getValueAt(selectedRow, 1));
        surname_area.setText((String) model.getValueAt(selectedRow, 2));
        mobile_area.setText((String) model.getValueAt(selectedRow, 3));
        address_area.setText((String) model.getValueAt(selectedRow, 4));
        password_area.setText((String) model.getValueAt(selectedRow, 5));                
    }//GEN-LAST:event_Users_TableMouseClicked

    private void update_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_userActionPerformed
        // USER UPDATE BUTTON
       String name = name_area.getText();
       String surname = surname_area.getText();
       String mobile = mobile_area.getText();
       String address = address_area.getText();
       String password = password_area.getText();
       
       int selectedRow = Users_Table.getSelectedRow();
       if(selectedRow == -1){
           if(model.getRowCount() == 0){
               messeage_area.setText("No data");
           }else{
           messeage_area.setText("Please click one of the user to change.");
           }
       }else{
           int id = (int) model.getValueAt(selectedRow,0);
           dbc.updateUser(id,name,surname,mobile,address,password);
           showUsers();
           messeage_area.setText("User has successfully updated");
       }
    }//GEN-LAST:event_update_userActionPerformed

    private void delete_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_userActionPerformed
       messeage_area.setText("");
       int selectedRow = Users_Table.getSelectedRow();
       if(selectedRow == -1){
           if(model.getRowCount() == 0){
               messeage_area.setText("No data");
           }else{
           messeage_area.setText("Please click one of the user to delete.");
           }
       }else{
           int id = (int) model.getValueAt(selectedRow,0);
           dbc.deleteUser(id);
           showUsers();
           messeage_area.setText("User has successfully deleted.");
       }       
    }//GEN-LAST:event_delete_userActionPerformed

    private void log_out_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_out_buttonActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_log_out_buttonActionPerformed

    private void log_out_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_out_buttonMouseClicked
        // TODO add your handling code here:  NOTHING TO DO HERE!!!!!!!!!!!!!!!!!!!!!!!!!
    }//GEN-LAST:event_log_out_buttonMouseClicked

    
    private void go_restaurant_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_go_restaurant_menuMouseClicked
        RestaurantForAdmin restaurant = new RestaurantForAdmin(null,true);          
        setVisible(false);
        restaurant.setVisible(true);
        dispose();
    }//GEN-LAST:event_go_restaurant_menuMouseClicked

    private void show_review_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_review_btnMouseClicked
        ReviewsForAdmin reviews_for_admin = new ReviewsForAdmin(null,true);
        setVisible(false);
        reviews_for_admin.setVisible(true);
        dispose();
    }//GEN-LAST:event_show_review_btnMouseClicked

    private void go_orderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_go_orderMouseClicked
        OrdersForAdmin orders_for_admin = new OrdersForAdmin(null,true);
        setVisible(false);
        orders_for_admin.setVisible(true);
        dispose();
    }//GEN-LAST:event_go_orderMouseClicked

    /**
     * @param args the command line arguments
     */
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UsersScreen dialog = new UsersScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SearchBar;
    private javax.swing.JTable Users_Table;
    private javax.swing.JButton add_user;
    private javax.swing.JTextField address_area;
    private javax.swing.JButton delete_user;
    private javax.swing.JButton go_order;
    private javax.swing.JButton go_restaurant_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton log_out_button;
    private javax.swing.JLabel messeage_area;
    private javax.swing.JTextField mobile_area;
    private javax.swing.JTextField name_area;
    private javax.swing.JTextField password_area;
    private javax.swing.JButton show_review_btn;
    private javax.swing.JTextField surname_area;
    private javax.swing.JButton update_user;
    // End of variables declaration//GEN-END:variables
}
