-- MySQL Script generated by MySQL Workbench
-- Sun Dec 25 20:53:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema foodorderV2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `foodorderV2` ;

-- -----------------------------------------------------
-- Schema foodorderV2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `foodorderV2` DEFAULT CHARACTER SET utf8 ;
USE `foodorderV2` ;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `surname` VARCHAR(32) NOT NULL,
  `mobile` VARCHAR(60) NOT NULL,
  `address` TEXT NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `imageurl` TEXT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `restaurant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurant` ;

CREATE TABLE IF NOT EXISTS `restaurant` (
  `restaurant_id` INT NOT NULL AUTO_INCREMENT,
  `restaurant_name` VARCHAR(80) NOT NULL,
  `restaurant_describtion` TEXT NULL,
  PRIMARY KEY (`restaurant_id`));


-- -----------------------------------------------------
-- Table `orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orders` ;

CREATE TABLE IF NOT EXISTS `orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `restaurant_restaurant_id` INT NOT NULL,
  `order_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`order_id`),
  INDEX `fk_orders_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_orders_restaurant1_idx` (`restaurant_restaurant_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_restaurant1`
    FOREIGN KEY (`restaurant_restaurant_id`)
    REFERENCES `restaurant` (`restaurant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `restaurant_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurant_item` ;

CREATE TABLE IF NOT EXISTS `restaurant_item` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `item_name` VARCHAR(55) NOT NULL,
  `item_catagory` VARCHAR(60) NOT NULL,
  `item_desc` VARCHAR(255) NOT NULL,
  `item_price` INT NOT NULL,
  `item_img` VARCHAR(45) NOT NULL,
  `restaurant_restaurant_id` INT NOT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_restaurant_item_restaurant1_idx` (`restaurant_restaurant_id` ASC) VISIBLE,
  CONSTRAINT `fk_restaurant_item_restaurant1`
    FOREIGN KEY (`restaurant_restaurant_id`)
    REFERENCES `restaurant` (`restaurant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payment` ;

CREATE TABLE IF NOT EXISTS `payment` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `total_price` INT NOT NULL,
  `payment_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `orders_order_id` INT NOT NULL,
  `quantity` INT NULL DEFAULT '1',
  PRIMARY KEY (`payment_id`),
  INDEX `fk_payment_orders1_idx` (`orders_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment_orders1`
    FOREIGN KEY (`orders_order_id`)
    REFERENCES `orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `review` ;

CREATE TABLE IF NOT EXISTS `review` (
  `review_id` INT NOT NULL AUTO_INCREMENT,
  `service_rev` INT NOT NULL,
  `delivery_rev` INT NOT NULL,
  `taste_rev` VARCHAR(45) NULL,
  `users_id` INT NOT NULL,
  `restaurant_restaurant_id` INT NOT NULL,
  PRIMARY KEY (`review_id`, `restaurant_restaurant_id`),
  INDEX `fk_review_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_review_restaurant1_idx` (`restaurant_restaurant_id` ASC) VISIBLE,
  CONSTRAINT `fk_review_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_restaurant1`
    FOREIGN KEY (`restaurant_restaurant_id`)
    REFERENCES `restaurant` (`restaurant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `delivery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivery` ;

CREATE TABLE IF NOT EXISTS `delivery` (
  `delivery_id` INT NOT NULL AUTO_INCREMENT,
  `orders_order_id` INT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`delivery_id`),
  INDEX `fk_delivery_orders1_idx` (`orders_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_delivery_orders1`
    FOREIGN KEY (`orders_order_id`)
    REFERENCES `orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin` ;

CREATE TABLE IF NOT EXISTS `admin` (
  `admin_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(80) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`admin_id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
